import { atomOneDark } from "react-syntax-highlighter/dist/cjs/styles/hljs";

// This is pretty much an extension of the atomOneLight theme
const customLight = {
  hljs: {
    fontSize: "12px",
    display: "block",
    overflowX: "auto",
    paddingBlock: "var(--tgph-spacing-5)",
    paddingInline: "var(--tgph-spacing-5)",
    color: "var(--tgph-black)",
    background: "var(--tgph-white)",
  },
  "hljs-comment": { color: "var(--tgph-gray-9)", fontStyle: "italic" },
  "hljs-quote": { color: "#a0a1a7", fontStyle: "italic" },
  "hljs-doctag": { color: "#a626a4" },
  "hljs-keyword": { color: "var(--tgph-purple-9)" },
  "hljs-formula": { color: "#a626a4" },
  "hljs-section": { color: "#e45649" },
  "hljs-name": { color: "#e45649" },
  "hljs-selector-tag": { color: "#e45649" },
  "hljs-deletion": { color: "#e45649" },
  "hljs-subst": { color: "#e45649" },
  "hljs-literal": { color: "var(--tgph-purple-11)" },
  "hljs-string": { color: "var(--tgph-green-11)" },
  "hljs-regexp": { color: "var(--tgph-yellow-11)" },
  "hljs-addition": { color: "var(--tgph-yellow-11)" },
  "hljs-attribute": { color: "var(--tgph-yellow-11)" },
  "hljs-meta-string": { color: "var(--tgph-yellow-11)" },
  "hljs-built_in": { color: "var(--tgph-purple-11)" },
  "hljs-class .hljs-title": { color: "#c18401" },
  "hljs-attr": { color: "#986801" },
  "hljs-variable": { color: "var(--tgph-purple-11)" },
  "hljs-template-variable": { color: "#986801" },
  "hljs-type": { color: "#986801" },
  "hljs-selector-class": { color: "#986801" },
  "hljs-selector-attr": { color: "#986801" },
  "hljs-selector-pseudo": { color: "#986801" },
  "hljs-number": { color: "#986801" },
  "hljs-symbol": { color: "var(--tgph-purple-11)" },
  "hljs-bullet": { color: "var(--tgph-blue-11)" },
  "hljs-link": { color: "var(--tgph-blue-11)", textDecoration: "underline" },
  "hljs-meta": { color: "var(--tgph-blue-11)" },
  "hljs-selector-id": { color: "var(--tgph-blue-11)" },
  "hljs-title": { color: "var(--tgph-blue-11)" },
  "hljs-emphasis": { fontStyle: "italic" },
  "hljs-strong": { fontWeight: "bold" },
};

export const lightCodeTheme = customLight;
export const darkCodeTheme = atomOneDark;
