name: Docs CI/CD

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate LLMs content
        run: yarn generate-llms

      - name: Type check
        run: yarn run type-check

      - name: Lint code
        run: yarn run lint

      - name: Check formatting
        run: yarn run format.check
